// ------------------------------------------------------------------------------------------------
//                typeEquality.generated.ts - Schema and plain type equality proof
// ------------------------------------------------------------------------------------------------

// This file is generated by scripts/generate-contract-surfaces.mjs. Do not edit by hand.

import type { z } from 'zod/v4';

import type { AgentArtifactDescriptor } from '../artifacts/types.js';
import type { AgentCapabilities } from '../capabilities/types.js';
import type { AgentEvent } from '../events/types.js';
import type { AgentError, AgentJsonValue, AgentProviderRefs } from '../foundation/types.js';
import type { AgentRequest, AgentRequestResolution } from '../requests/types.js';
import type { AgentSessionBinding, AgentSessionConfiguration, AgentSessionOpenInput } from '../sessions/types.js';
import type { AgentItemSnapshot, AgentTurnInputContent, AgentTurnInterruptionInput, AgentTurnRunInput } from '../turns/types.js';
import { AgentArtifactDescriptorSchema } from './artifacts.js';
import { AgentCapabilitiesSchema } from './capabilities.js';
import { AgentEventSchema } from './events.js';
import { AgentErrorSchema, AgentJsonValueSchema, AgentProviderRefsSchema } from './foundation.js';
import { AgentRequestResolutionSchema, AgentRequestSchema } from './requests.js';
import { AgentSessionBindingSchema, AgentSessionConfigurationSchema, AgentSessionOpenInputSchema } from './sessions.js';
import { AgentItemSnapshotSchema, AgentTurnInputContentSchema, AgentTurnInterruptionInputSchema, AgentTurnRunInputSchema } from './turns.js';

type Extends<Left, Right> = [Left] extends [Right] ? true : false;
type Assert<Value extends true> = Value;

export type AgentProtocolSchemaTypeAssertions = readonly [
  Assert<Extends<z.output<typeof AgentJsonValueSchema>, AgentJsonValue>>,
  Assert<Extends<AgentJsonValue, z.output<typeof AgentJsonValueSchema>>>,
  Assert<Extends<z.output<typeof AgentProviderRefsSchema>, AgentProviderRefs>>,
  Assert<Extends<AgentProviderRefs, z.output<typeof AgentProviderRefsSchema>>>,
  Assert<Extends<z.output<typeof AgentErrorSchema>, AgentError>>,
  Assert<Extends<AgentError, z.output<typeof AgentErrorSchema>>>,
  Assert<Extends<z.output<typeof AgentSessionBindingSchema>, AgentSessionBinding>>,
  Assert<Extends<AgentSessionBinding, z.output<typeof AgentSessionBindingSchema>>>,
  Assert<Extends<z.output<typeof AgentSessionConfigurationSchema>, AgentSessionConfiguration>>,
  Assert<Extends<AgentSessionConfiguration, z.output<typeof AgentSessionConfigurationSchema>>>,
  Assert<Extends<z.output<typeof AgentSessionOpenInputSchema>, AgentSessionOpenInput>>,
  Assert<Extends<AgentSessionOpenInput, z.output<typeof AgentSessionOpenInputSchema>>>,
  Assert<Extends<z.output<typeof AgentTurnInputContentSchema>, AgentTurnInputContent>>,
  Assert<Extends<AgentTurnInputContent, z.output<typeof AgentTurnInputContentSchema>>>,
  Assert<Extends<z.output<typeof AgentTurnRunInputSchema>, AgentTurnRunInput>>,
  Assert<Extends<AgentTurnRunInput, z.output<typeof AgentTurnRunInputSchema>>>,
  Assert<Extends<z.output<typeof AgentTurnInterruptionInputSchema>, AgentTurnInterruptionInput>>,
  Assert<Extends<AgentTurnInterruptionInput, z.output<typeof AgentTurnInterruptionInputSchema>>>,
  Assert<Extends<z.output<typeof AgentItemSnapshotSchema>, AgentItemSnapshot>>,
  Assert<Extends<AgentItemSnapshot, z.output<typeof AgentItemSnapshotSchema>>>,
  Assert<Extends<z.output<typeof AgentRequestSchema>, AgentRequest>>,
  Assert<Extends<AgentRequest, z.output<typeof AgentRequestSchema>>>,
  Assert<Extends<z.output<typeof AgentRequestResolutionSchema>, AgentRequestResolution>>,
  Assert<Extends<AgentRequestResolution, z.output<typeof AgentRequestResolutionSchema>>>,
  Assert<Extends<z.output<typeof AgentCapabilitiesSchema>, AgentCapabilities>>,
  Assert<Extends<AgentCapabilities, z.output<typeof AgentCapabilitiesSchema>>>,
  Assert<Extends<z.output<typeof AgentArtifactDescriptorSchema>, AgentArtifactDescriptor>>,
  Assert<Extends<AgentArtifactDescriptor, z.output<typeof AgentArtifactDescriptorSchema>>>,
  Assert<Extends<z.output<typeof AgentEventSchema>, AgentEvent>>,
  Assert<Extends<AgentEvent, z.output<typeof AgentEventSchema>>>,
];
