// ------------------------------------------------------------------------------------------------
//                capabilities.ts - Plain agent protocol exports
// ------------------------------------------------------------------------------------------------

// This file is generated by scripts/generate-contract-surfaces.mjs. Do not edit by hand.

export * from '../capabilities/index.js';
